# This file is machine-generated - editing it directly is not advised

julia_version = "1.9.2"
manifest_format = "2.0"
project_hash = "1bf5266769fa7bab5df9ae81c77be02aa5fe3771"

[[deps.AquaticTests]]
deps = ["Markdown"]
git-tree-sha1 = "9526bc8b4e8bd0e6f1e4b1e7acfd76a18ae80806"
repo-rev = "main"
repo-url = "https://github.com/chem330/AquaticTests.jl"
uuid = "ef2b17a9-53be-439a-85ce-aa94808be9bb"
version = "1.0.0-DEV"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"
